# Generated by Django 2.2.4 on 2019-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_seminar_link_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='document',
        ),
        migrations.AddField(
            model_name='certification',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seminar',
            name='document_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='link_proof',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
